const cateTool = [
  {
    title: "AI Assistants",
    tools: [
      { name: "ChatGPT", description: "OpenAI's AI assistant for conversations.", url: "https://chat.openai.com/" },
      { name: "Gemini", description: "AI chatbot by Google.", url: "https://gemini.google.com/" },
      { name: "Bing Chat (Microsoft Copilot)", description: "AI assistant built into Microsoft 365 apps and Windows.", url: "https://copilot.microsoft.com/" },
      { name: "Perplexity AI", description: "AI-powered search engine with citations.", url: "https://www.perplexity.ai/" },
      { name: "Claude 3", description: "Anthropic’s helpful AI assistant, great for writing and reasoning.", url: "https://claude.ai/" },
      { name: "You.com", description: "AI search engine and assistant with productivity tools.", url: "https://you.com/" },
      { name: "DeepSeek", description: "Chinese open-source AI assistant with multilingual support.", url: "https://deepseek.com/" },
      { name: "Character AI", description: "Conversational AI bots with personalities.", url: "https://beta.character.ai/" },
      { name: "Meta AI", description: "AI assistant by Meta.", url: "https://ai.meta.com/" },
      { name: "Poe", description: "Platform for interacting with various AI chatbots.", url: "https://poe.com/" },
      { name: "Replika", description: "AI companion that learns and grows with you.", url: "https://replika.com/" },
      { name: "Socratic by Google", description: "AI-powered learning app for homework help.", url: "https://socratic.org/" },
      { name: "Elicit", description: "AI research assistant to find and synthesize information.", url: "https://elicit.org/" },
      { name: "Monica AI", description: "Your everyday AI assistant in your browser.", url: "https://monica.im/" },
      { name: "Tome", description: "AI-powered storytelling format.", url: "https://tome.app/" },
      { name: "Andi Search", description: "Generative AI search engine that answers questions directly.", url: "https://andisearch.com/" },
      { name: "Phind", description: "AI search engine for developers.", url: "https://www.phind.com/" },
      { name: "Talk to Books by Google", description: "Explore ideas and discover books through conversation.", url: "https://books.google.com/talktobooks/" },
      { name: "Bardeen AI", description: "AI automation for workflows.", url: "https://www.bardeen.ai/" },
      { name: "Eightify", description: "AI-powered YouTube video summarizer.", url: "https://eightify.app/" }
    ]
  },
  {
    title: "Content Creation (Text & Copywriting)",
    tools: [
      { name: "Copy.ai", description: "AI copywriting and marketing tool.", url: "https://www.copy.ai/" },
      { name: "Jasper", description: "AI writing assistant for marketers and teams.", url: "https://www.jasper.ai/" },
      { name: "Writesonic", description: "AI content generator for blogs, ads, and more.", url: "https://writesonic.com/" },
      { name: "Notion AI", description: "Built-in AI assistant inside Notion for content and task help.", url: "https://www.notion.so/product/ai" },
      { name: "Wordtune", description: "AI-powered rephrasing and writing enhancement tool.", url: "https://www.wordtune.com/" },
      { name: "GrammarlyGO", description: "AI-powered writing assistant from Grammarly.", url: "https://www.grammarly.com/ai" },
      { name: "Anyword", description: "AI for creating high-performing marketing copy.", url: "https://anyword.com/" },
      { name: "Sudowrite", description: "AI creative writing tool for fiction and storytelling.", url: "https://www.sudowrite.com/" },
      { name: "Scalenut", description: "AI content planner and writer for SEO.", url: "https://www.scalenut.com/" },
      { name: "HyperWrite", description: "Smart AI writing copilot and auto-pilot browser agent.", url: "https://www.hyperwriteai.com/" },
      { name: "Rytr", description: "AI writing assistant that helps you create high-quality content.", url: "https://rytr.me/" },
      { name: "Surfer SEO", description: "AI-powered content intelligence for SEO.", url: "https://surferseo.com/" },
      { name: "Content at Scale", description: "AI content generation for long-form, SEO-optimized articles.", url: "https://contentatscale.ai/" },
      { name: "Peppertype.ai", description: "AI content generator for various content types.", url: "https://www.peppertype.ai/" },
      { name: "QuillBot", description: "AI paraphrasing tool and grammar checker.", url: "https://quillbot.com/" },
      { name: "ShortlyAI", description: "AI writing tool to generate blog posts, articles, and more.", url: "https://www.shortlyai.com/" },
      { name: "Articoolo", description: "AI article writer that generates unique content.", url: "https://articoolo.com/" },
      { name: "ClosersCopy", description: "AI copywriting software for sales and marketing.", url: "https://closerscopy.com/" },
      { name: "Frase.io", description: "AI content optimization and creation platform.", url: "https://www.frase.io/" },
      { name: "GrowthBar", description: "SEO content tool with AI writing features.", url: "https://www.growthbar.com/" },
      { name: "TextCortex AI", description: "Personalized AI writing assistant for every platform.", url: "https://textcortex.com/" },
      { name: "Simplified", description: "All-in-one AI platform for design, video, and writing.", url: "https://simplified.com/" },
      { name: "AI Writer", description: "Generates articles and blog posts from a headline.", url: "https://ai-writer.com/" },
      { name: "InferKit", description: "AI text generation API for creative writing.", url: "https://inferkit.com/" },
      { name: "CopyMonkey", description: "AI for Amazon listings and product descriptions.", url: "https://copymonkey.ai/" },
      { name: "PostcardMania AI Copywriter", description: "AI tool for generating direct mail copy.", url: "https://www.postcardmania.com/ai-copywriter/" },
      { name: "Outranking", description: "AI-powered content creation and optimization platform.", url: "https://www.outranking.io/" },
      { name: "ParagraphAI", description: "AI writing assistant for email, articles, and more.", url: "https://paragraphai.com/" },
      { name: "ContentBot.ai", description: "AI writer for blog posts, ads, and marketing copy.", url: "https://contentbot.ai/" },
      { name: "Sapling.ai", description: "AI assistant for business communication.", url: "https://sapling.ai/" }
    ]
  },
  {
    title: "Image Generation",
    tools: [
      { name: "DALL·E 3", description: "OpenAI’s image generation from text prompts.", url: "https://openai.com/dall-e" },
      { name: "Midjourney", description: "AI tool that creates art from text prompts.", url: "https://www.midjourney.com/" },
      { name: "Leonardo AI", description: "Fast-growing creative AI for high-quality images.", url: "https://leonardo.ai/" },
      { name: "Playground AI", description: "Free AI image generator for casual and commercial use.", url: "https://playgroundai.com/" },
      { name: "Adobe Firefly", description: "AI art and image tools built into Adobe apps.", url: "https://www.adobe.com/sensei/generative-ai/firefly.html" },
      { name: "Craiyon (DALL-E mini)", description: "Lightweight, free AI image generator.", url: "https://www.craiyon.com/" },
      { name: "Dream by Wombo", description: "Create AI art instantly with custom styles.", url: "https://dream.ai/" },
      { name: "NightCafe", description: "Create, share, and explore AI-generated art.", url: "https://creator.nightcafe.studio/" },
      { name: "Stable Diffusion", description: "Open-source text-to-image diffusion model.", url: "https://stability.ai/stable-diffusion" },
      { name: "Artbreeder", description: "AI tool for creating new images by mixing and evolving existing ones.", url: "https://www.artbreeder.com/" },
      { name: "DeepArt.io", description: "Transforms photos into art using styles of famous paintings.", url: "https://deepart.io/" },
      { name: "RunDiffusion", description: "Cloud-based Stable Diffusion for fast image generation.", url: "https://rundiffusion.com/" },
      { name: "Lexica Art", description: "Search engine for Stable Diffusion images and prompts.", url: "https://lexica.art/" },
      { name: "PicFinder.AI", description: "Endless stream of AI-generated images from text.", url: "https://picfinder.ai/" },
      { name: "Bing Image Creator", description: "Create images from text with DALL-E 3 powered by Copilot.", url: "https://www.bing.com/images/create" },
      { name: "StarryAI", description: "AI art generator app for iOS and Android.", url: "https://starryai.com/" },
      { name: "Fotor AI Image Generator", description: "Online AI image generator and photo editor.", url: "https://www.fotor.com/features/ai-image-generator/" },
      { name: "Canva Text to Image", description: "Integrated AI image generator within Canva.", url: "https://www.canva.com/features/ai-image-generator/" },
      { name: "Getimg.ai", description: "Suite of AI tools for image generation and editing.", url: "https://getimg.ai/" },
      { name: "Facetune AI", description: "AI photo editor for selfies and portraits.", url: "https://www.facetuneapp.com/" }
    ]
  },
  {
    title: "Video Generation & Editing",
    tools: [
      { name: "RunwayML", description: "AI video editing and generation tool.", url: "https://runwayml.com/" },
      { name: "Pika", description: "Text-to-video AI for creators.", url: "https://pika.art/" },
      { name: "Synthesia", description: "AI avatar and video generation platform.", url: "https://www.synthesia.io/" },
      { name: "HeyGen", description: "AI presenter videos with avatars and voice cloning.", url: "https://www.heygen.com/" },
      { name: "OpusClip", description: "AI tool to repurpose videos into viral short clips.", url: "https://www.opus.pro/" },
      { name: "Fliki", description: "Turn text into videos with AI voiceovers and stock visuals.", url: "https://fliki.ai/" },
      { name: "Animoto AI", description: "Easy drag-and-drop video generator powered by AI.", url: "https://animoto.com/" },
      { name: "Descript", description: "All-in-one audio and video editor with AI features.", url: "https://www.descript.com/" },
      { name: "InVideo AI", description: "AI video creation for marketing and social media.", url: "https://invideo.io/" },
      { name: "Pictory AI", description: "Automatically create short, highly shareable brand videos.", url: "https://pictory.ai/" },
      { name: "DeepMotion", description: "AI motion capture for 3D animation.", url: "https://www.deepmotion.com/" },
      { name: "Waymark", description: "AI-generated local TV commercials.", url: "https://www.waymark.com/" },
      { name: "Hour One", description: "AI-powered realistic virtual human videos.", url: "https://hourone.ai/" },
      { name: "Viide.ai", description: "AI video editor for quick social media content.", url: "https://viide.ai/" },
      { name: "Gling", description: "AI video editor that removes silences and bad takes.", url: "https://gling.ai/" },
      { name: "Vidyo.ai", description: "Turn long videos into short clips for social media.", url: "https://vidyo.ai/" },
      { name: "Veed.io", description: "Online video editor with AI features like subtitles.", url: "https://www.veed.io/" },
      { name: "CapCut AI", description: "Free video editing app with AI features for mobile.", url: "https://www.capcut.com/" },
      { name: "Simplified Video Editor", description: "AI-powered video creation and editing.", url: "https://simplified.com/video-editor/" },
      { name: "Raw Shorts", description: "AI video maker for animated explainers and marketing videos.", url: "https://www.rawshorts.com/" }
    ]
  },
  {
    title: "Voice & Music",
    tools: [
      { name: "ElevenLabs", description: "Realistic AI voice generation and cloning.", url: "https://www.elevenlabs.io/" },
      { name: "Voicemod", description: "Real-time AI voice changer for gaming and streaming.", url: "https://www.voicemod.net/" },
      { name: "Suno", description: "AI tool that generates full songs from text prompts.", url: "https://suno.ai/" },
      { name: "Boomy", description: "Create original music with AI in seconds.", url: "https://www.boomy.com/" },
      { name: "Udio", description: "Next-gen AI music composer with vocals.", url: "https://www.udio.com/" },
      { name: "Aiva", description: "AI composer for soundtracks and classical music.", url: "https://www.aiva.ai/" },
      { name: "Soundraw", description: "AI music generator for creators.", url: "https://soundraw.io/" },
      { name: "Murf.ai", description: "AI voice generator for realistic text-to-speech.", url: "https://murf.ai/" },
      { name: "Lovo.ai", description: "AI voice generator and text-to-speech platform.", url: "https://www.lovo.ai/" },
      { name: "WellSaid Labs", description: "Create voiceovers using AI voices.", url: "https://www.wellsaidlabs.com/" },
      { name: "Resemble.ai", description: "AI voice cloning and generation platform.", url: "https://www.resemble.ai/" },
      { name: "Amper Music", description: "AI music composer and generator.", url: "https://www.ampermusic.com/" },
      { name: "Jukebox by OpenAI", description: "AI that generates music with singing.", url: "https://openai.com/blog/jukebox/" },
      { name: "Audiocraft by Meta", description: "Generative AI for audio and music from text.", url: "https://ai.meta.com/blog/audiocraft-generative-ai-audio-music-generation/" },
      { name: "Splash Music", description: "AI music creation for games and media.", url: "https://www.splashmusic.com/" },
      { name: "NaturalReader", description: "Text to speech online with natural voices.", url: "https://www.naturalreaders.com/" },
      { name: "Play.ht", description: "AI voice generator and realistic text to speech.", url: "https://play.ht/" },
      { name: "Voicify AI", description: "AI voice creation for various applications.", url: "https://voicify.ai/" },
      { name: "Riffusion", description: "Real-time music generation with AI.", url: "https://www.riffusion.com/" },
      { name: "TuneFlow", description: "AI-powered music co-creation platform.", url: "https://www.tuneflow.com/" }
    ]
  },
  {
    title: "AI Model Hosting & Development Tools",
    tools: [
      { name: "Ollama", description: "Local AI model hosting platform.", url: "https://ollama.ai/" },
      { name: "Hugging Face", description: "Platform for machine learning models and datasets.", url: "https://huggingface.co/" },
      { name: "Replicate", description: "Run AI models in the cloud with a few lines of code.", url: "https://replicate.com/" },
      { name: "RunPod", description: "GPU cloud for AI training and inference.", url: "https://www.runpod.io/" },
      { name: "Weights & Biases", description: "Developer tools for MLOps.", url: "https://wandb.ai/" },
      { name: "MLflow", description: "Open source platform for the machine learning lifecycle.", url: "https://mlflow.org/" },
      { name: "TensorFlow", description: "End-to-end open source platform for machine learning.", url: "https://www.tensorflow.org/" },
      { name: "PyTorch", description: "Open source machine learning framework.", url: "https://pytorch.org/" },
      { name: "Keras", description: "High-level neural networks API.", url: "https://keras.io/" },
      { name: "Scikit-learn", description: "Machine learning library for Python.", url: "https://scikit-learn.org/" },
      { name: "Rasa", description: "Open source conversational AI framework.", url: "https://rasa.com/" },
      { name: "OpenVINO", description: "Open-source toolkit for optimizing and deploying AI inference.", url: "https://www.openvino.ai/" },
      { name: "DeepMind", description: "Leading AI research company by Google.", url: "https://deepmind.google/" },
      { name: "Papers With Code", description: "Free resource with machine learning papers and code.", url: "https://paperswithcode.com/" },
      { name: "AI Dungeon", description: "AI-powered text adventure game using GPT-3.", url: "https://aidungeon.io/" },
      { name: "Google Cloud AI Platform", description: "Managed service for machine learning development.", url: "https://cloud.google.com/ai-platform" },
      { name: "Azure Machine Learning", description: "Cloud-based service for machine learning lifecycle.", url: "https://azure.microsoft.com/en-us/products/machine-learning" },
      { name: "Amazon SageMaker", description: "Fully managed machine learning service.", url: "https://aws.amazon.com/sagemaker/" },
      { name: "DataRobot", description: "Automated machine learning platform.", url: "https://www.datarobot.com/" },
      { name: "Domino Data Lab", description: "Data science platform for enterprise.", url: "https://www.dominodatalab.com/" }
    ]
  },
  {
    title: "Productivity & Business AI",
    tools: [
      { name: "Otter.ai", description: "AI meeting assistant that records, transcribes, and summarizes.", url: "https://otter.ai/" },
      { name: "Fireflies.ai", description: "AI meeting notes and conversation intelligence.", url: "https://fireflies.ai/" },
      { name: "Krisp", description: "AI-powered noise cancellation for calls.", url: "https://krisp.ai/" },
      { name: "Gamma", description: "AI-powered presentation maker.", url: "https://gamma.app/" },
      { name: "Beautiful.ai", description: "AI presentation software with smart templates.", url: "https://www.beautiful.ai/" },
      { name: "Motion", description: "AI scheduling and project management.", url: "https://www.usemotion.com/" },
      { name: "ClickUp AI", description: "AI features integrated into ClickUp for task management.", url: "https://clickup.com/features/ai/" },
      { name: "Monday.com AI", description: "AI tools within Monday.com for workflow automation.", url: "https://monday.com/lp/ai/" },
      { name: "Miro AI", description: "AI features for brainstorming and diagramming in Miro.", url: "https://miro.com/ai/" },
      { name: "Tome", description: "AI-powered storytelling format for presentations.", url: "https://tome.app/" },
      { name: "Rows", description: "Spreadsheet with built-in AI for data analysis.", url: "https://rows.com/" },
      { name: "Zapier AI", description: "Connect apps and automate workflows with AI.", url: "https://zapier.com/ai" },
      { name: "Make (formerly Integromat)", description: "Visual platform for automating workflows with AI integrations.", url: "https://www.make.com/" },
      { name: "Axiom.ai", description: "Browser automation with AI.", url: "https://axiom.ai/" },
      { name: "Browse.ai", description: "Extract and monitor data from any website without code.", url: "https://browse.ai/" },
      { name: "Airtable AI", description: "AI functionality within Airtable for data management.", url: "https://www.airtable.com/ai" },
      { name: "Formulas by Google Sheets", description: "AI-powered formula suggestions in Google Sheets.", url: "https://support.google.com/docs/answer/10321453" },
      { name: "XLookup by Microsoft Excel", description: "Advanced lookup function with AI enhancements.", url: "https://support.microsoft.com/en-us/office/xlookup-function-f538eec3-6d09-4185-bc95-8d59fd1e75a9" },
      { name: "DocuSign AI", description: "AI for contract analysis and agreement management.", url: "https://www.docusign.com/solutions/ai" },
      { name: "Salesforce Einstein", description: "AI for CRM to enhance sales, service, and marketing.", url: "https://www.salesforce.com/products/einstein/" }
    ]
  },
  {
    title: "Design & UX AI",
    tools: [
      { name: "Midjourney", description: "AI tool that creates art from text prompts, also used for design inspiration.", url: "https://www.midjourney.com/" },
      { name: "Uizard", description: "AI-powered UI design tool that turns text to wireframes.", url: "https://uizard.io/" },
      { name: "Figma AI", description: "AI plugins and features for design in Figma.", url: "https://www.figma.com/" },
      { name: "AdCreative.ai", description: "AI ad creative generator for higher conversions.", url: "https://www.adcreative.ai/" },
      { name: "Designs.ai", description: "AI design platform for logos, videos, banners, and mockups.", url: "https://designs.ai/" },
      { name: "Khroma", description: "AI-powered color palette generator.", url: "https://www.khroma.co/" },
      { name: "Fronty", description: "AI-powered website builder that converts images to HTML/CSS.", url: "https://fronty.com/" },
      { name: "VanceAI", description: "AI image enhancer, upscaler, denoiser, and more.", url: "https://vanceai.com/" },
      { name: "Remove.bg", description: "AI tool to remove image backgrounds automatically.", url: "https://www.remove.bg/" },
      { name: "Cleanup.pictures", description: "AI image editing for removing objects, text, or defects.", url: "https://cleanup.pictures/" },
      { name: "Let's Enhance", description: "AI photo enhancer and upscaler.", url: "https://letsenhance.io/" },
      { name: "DeepMotion (for 3D design)", description: "AI motion capture for 3D animation and character design.", url: "https://www.deepmotion.com/" },
      { name: "SketchUp Diffusion", description: "AI text-to-image for architectural designs.", url: "https://www.sketchup.com/products/diffusion" },
      { name: "Autodesk Generative Design", description: "AI for generating design options in engineering.", url: "https://www.autodesk.com/solutions/generative-design" },
      { name: "NVIDIA Canvas", description: "AI painting application for artists.", url: "https://www.nvidia.com/en-us/studio/canvas/" },
      { name: "Clipdrop", description: "Suite of AI tools for creators including image upscaling, relighting, and cleanup.", url: "https://clipdrop.co/" },
      { name: "IconifyAI", description: "Generate app icons with AI.", url: "https://iconifyai.com/" },
      { name: "Diagrams.net AI", description: "AI assistance for creating diagrams.", url: "https://www.diagrams.net/" },
      { name: "Looka", description: "AI-powered logo maker and brand identity design.", url: "https://looka.com/" },
      { name: "Fontjoy", description: "AI font pairing generator.", url: "https://fontjoy.com/" }
    ]
  },
  {
    title: "Code & Development AI",
    tools: [
      { name: "GitHub Copilot", description: "AI pair programmer for code suggestions.", url: "https://github.com/features/copilot" },
      { name: "Tabnine", description: "AI code completion for faster development.", url: "https://www.tabnine.com/" },
      { name: "Amazon CodeWhisperer", description: "AI coding companion that generates code suggestions.", url: "https://aws.amazon.com/codewhisperer/" },
      { name: "Replit Ghostwriter", description: "AI code generation and completion in Replit IDE.", url: "https://replit.com/site/ghostwriter" },
      { name: "OpenAI Codex", description: "AI model that translates natural language to code.", url: "https://openai.com/blog/openai-codex/" },
      { name: "Sourcegraph Cody", description: "AI coding assistant that understands your codebase.", url: "https://about.sourcegraph.com/cody" },
      { name: "ChatGPT (for code generation)", description: "Can generate code snippets, debug, and explain code.", url: "https://chat.openai.com/" },
      { name: "Google Gemini (for code generation)", description: "Capable of generating and explaining code across languages.", url: "https://gemini.google.com/" },
      { name: "DeepCode.ai (now Snyk Code)", description: "AI static code analysis for security vulnerabilities.", url: "https://snyk.io/product/snyk-code/" },
      { name: "Mutable.ai", description: "AI for automated refactoring and code modernization.", url: "https://mutable.ai/" },
      { name: "Kite (discontinued)", description: "AI code completion for Python, Java, and JavaScript (Note: Discontinued but influential).", url: "https://www.kite.com/" },
      { name: "CodeGPT", description: "AI for generating and refactoring code, available as IDE extensions.", url: "https://codegpt.co/" },
      { name: "Axiom.ai", description: "Browser automation with AI for web scraping and data entry.", url: "https://axiom.ai/" },
      { name: "Buildship", description: "AI for building backend APIs and workflows.", url: "https://www.buildship.com/" },
      { name: "Appy Pie AppMakr AI", description: "AI app builder for no-code mobile apps.", url: "https://www.appypie.com/ai-app-maker/" },
      { name: "Debuild", description: "AI-powered web app builder from text descriptions.", url: "https://debuild.app/" },
      { name: "Adalo", description: "No-code app builder with AI integrations.", url: "https://www.adalo.com/" },
      { name: "Bubble", description: "No-code platform to build web applications with AI plugins.", url: "https://bubble.io/" },
      { name: "Webflow AI", description: "AI features integrated into Webflow for web design and development.", url: "https://webflow.com/ai" },
      { name: "Vercel AI SDK", description: "Tools for building AI-powered applications with Next.js.", url: "https://sdk.vercel.ai/" }
    ]
  }
];